version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
      
  toro-quotes:
    image: toroinvestimentos/quotesmock
    ports:
      - "8080:8080"
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: npm start
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - PORT=8000
    links:
      - mongo

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: npm start
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - PORT=8001
    links:
      - mongo

  ws:
    build:
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    command: npm start
    volumes:
      - ./ws:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    environment:
      - PORT=8002

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    environment:
      - PORT=80

networks:
  app-network:
    driver: bridge